---
#management.server.address: 127.0.0.1
#management.endpoint.shutdown.enabled: true
management.endpoints.web.exposure.include: health

mybatis.mapper-locations: classpath*:mapper/*Mapper.xml

pagehelper.helperDialect: mysql
pagehelper.reasonable: false
pagehelper.supportMethodsArguments: true
pagehelper.params=count: countSql

springfox.documentation.enabled: true

server:
  port: 18080
spring:
  application:
    name: commons-test-web
  mvc.servlet.load-on-startup: 1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.80.130:3306/gddc_admin?setUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123456
  cloud:
    loadbalancer: #LoadBalancerClientsProperties
      retry:
        enabled: false #默认true  
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8858    
        
feign:
  sentinel:
    enabled: true #默认false
  client:
    config:
      default:
        connectTimeout: 500
        readTimeout: 3000

commons:
  sentinel: 
    cluster:
      enabled: true
      serverAddr: localhost
      serverPort: 11111      
  mybatis:
    mapperScan:
      basePackages: io.github.icodegarden.commons.test.web
  redis:
    pool: 
      host: r-bp1pozc9d7ehti3jbf.redis.rds.aliyuncs.com
      port: 6379
      password: Aa@653210000  




# 单个文件大小
spring.servlet.multipart.max-file-size: 5000MB
# 总上传的数据大小
spring.servlet.multipart.max-request-size: 5000MB