---
#management.server.address: 127.0.0.1
#management.endpoint.shutdown.enabled: true
management.endpoints.web.exposure.include: health

commons.web.webfilter.processingRequestCount.enabled: false #网关不需要这个

server:
  port: 16680
  shutdown: graceful
spring:
  lifecycle.timeout-per-shutdown-phase: 20s
  application:
    name: commons-apigateway
  cloud:
    loadbalancer: #LoadBalancerClientsProperties
      retry:
        enabled: false #默认true    
    gateway:   #https://docs.spring.io/spring-cloud-gateway/docs/current/reference/html/appendix.html
      discovery.locator.enabled: true #默认false，与服务发现集成，例如nacos
      httpclient:    #对下游服务的配置 org.springframework.cloud.gateway.config.HttpClientProperties
        connect-timeout: 1000    #The connect timeout in millis, the default is 45s.
        response-timeout: 5000    #The response timeout.
        pool.type: FIXED    #ELASTIC,FIXED,DISABLED.  Type of pool for HttpClient to use, defaults to ELASTIC.
        pool.acquire-timeout: 1000  #Only for type FIXED, the maximum time in millis to wait for acquiring.
        pool.eviction-interval: 0   #默认0.定时检查和回收连接池中不健康的连接的时间间隔，默认=0是不会生效；netty 连接池中的连接只有在取和放的时候才会根据max-idle-time判断连接是否需要释放 Perform regular eviction checks in the background at a specified interval. Disabled by default ({@link Duration#ZERO})
        pool.max-connections: 500    #Only for type FIXED, the maximum number of connections before starting pending acquisition on existing ones.
        pool.max-idle-time: 60000   #Time in millis after which the channel will be closed. If NULL, there is no max idle time.
        pool.max-life-time: 600000  #Duration after which the channel will be closed. If NULL, there is no max life time.
#        pool.metrics: false   #默认false.Enables channel pools metrics to be collected and registered in Micrometer. Disabled by default.
#        pool.name: proxy   #The channel pool map name, defaults to proxy.
#        proxy.host:   #Hostname for proxy configuration of Netty HttpClient.
#        proxy.non-proxy-hosts-pattern:    #Regular expression (Java) for a configured list of hosts. that should be reached directly, bypassing the proxy
#        proxy.username:    #Username for proxy configuration of Netty HttpClient.
#        proxy.password:    #Password for proxy configuration of Netty HttpClient.
#        proxy.port:    #Port for proxy configuration of Netty HttpClient.
#        proxy.type:    #proxyType for proxy configuration of Netty HttpClient.
#        max-header-size:   #The max response header size.
      default-filters:   
      - StripPrefix=1      
      - RemoveRequestHeader=X-Internal-Rpc
      - RemoveRequestHeader=Authorization



