spring:
  cloud:
    gateway:   
      default-filters:   #不用修改，放在这里是因为openapi也有一个不同的配置
      - StripPrefix=1      
      - RemoveRequestHeader=X-Internal-Rpc
      - RemoveRequestHeader=Authorization  
#      - RequestHeaderSize=102400B      #不设置时默认不限制
#      - name: RequestSize #不设置时默认5MB
#        args:
#          maxSize: 2048MB      
      routes:
      - id: admin_route
        uri: lb://gddc-admin
        predicates:
        - Path=/admin/**
#        metadata:
#          connect-timeout: 1000
#          response-timeout: 3000
      - id: manage_route
        uri: lb://gddc-manage
        predicates:
        - Path=/manage/**      
    sentinel: #sentinel-springcloud的自动配置
      transport:
        port: 8719
        dashboard: localhost:8858           
             
commons: 
  sentinel: #CommonsSentinelProperties.java
    cluster:
      enabled: true
      serverAddr: localhost
      serverPort: 11111
    nacos:
      dynamicRuleGroupId: Sentinel                 
  gateway:    
   security: #CommonsGatewaySecurityProperties.java
     jwt:
       issuer: icodegarden
       secretKey: icodegarden@jwt0123456789                           


